services:
  mega_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mega_app

    ports:
      - "5001:5000"
    env_file:
      - .dockerenv

    command: sh -c "uvicorn app:app --reload --host 0.0.0.0 --port=5000"
